[package]
name = "rustls-spiffe"
version = "0.1.0"
edition = "2024"
description = "SPIFFE Integration with Rustls to provide Server and Client certs/keys and CA bundle"
license = "MIT or Apache-2.0"

[dependencies]
